### ISSUE TITLE
Fails to load DLL on windows

### ISSUE THREAD

**Issue by postlund** [bdraco/chacha20poly1305-reuseable#9]
**Describe the bug**
My pyatv GitHub actions jobs does not seem to work on Windows anymore. I get this error:

```
...
pyatv\support\chacha20.py:2: in <module>

    from chacha20poly1305_reuseable import ChaCha20Poly1305Reusable as ChaCha20Poly1305

E   ImportError: DLL load failed while importing chacha20poly1305_reuseable: %1 is not a valid Win32 application.
```
**To Reproduce**

In my case I just import the library on a Windows machine (`windows-latest` on GitHub in this case).
**Additional context**

https://github.com/postlund/pyatv/actions/runs/4728869785/jobs/8395410792?pr=1956

**Comment by bdraco** [comment]
It looks like ciwheelbuild has some fixes for windows builds https://github.com/pypa/cibuildwheel/releases

I'll bump the version and rebuild

**Comment by bdraco** [comment]
Opened https://github.com/bdraco/chacha20poly1305-reuseable/pull/10 to test on windows and use the 2019 images + new ciwheelbuild

Lets see how it goes

**Comment by bdraco** [comment]
https://github.com/bdraco/chacha20poly1305-reuseable/actions/runs/4826157736

Its rebuilding now with the newer version + the base image downgraded to windows 2019

**Comment by bdraco** [comment]
Feel free to reach out on discard if there is still an issue.  I am likely to miss any updates here

**Comment by bdraco** [comment]
First run failed

trying again

https://github.com/bdraco/chacha20poly1305-reuseable/actions/runs/4826231708

**Comment by bdraco** [comment]
windows-2019 has trouble with utf-8
so
one more attempt

https://github.com/bdraco/chacha20poly1305-reuseable/actions/runs/4826325094

**Comment by bdraco** [comment]
Looks like 3rd time was a charm. Wheels should be up on pypi in the next 30m

**Comment by postlund** [comment]
I do see the same issue still, anything I need to do?

**Comment by bdraco** [comment]
https://stackoverflow.com/questions/19019720/importerror-dll-load-failed-1-is-not-a-valid-win32-application-but-the-dlls

This is all I've found so far

**Comment by bdraco** [comment]
We are building both 32bit and 64bit wheels.

Maybe the wrong one is getting installed somehow

**Comment by bdraco** [comment]
```
13 wheels produced in 10 minutes:
  chacha20poly1305_reuseable-0.2.5-cp310-cp310-win32.whl            66 kB
  chacha20poly1305_reuseable-0.2.5-cp310-cp310-win_amd64.whl        66 kB
  chacha20poly1305_reuseable-0.2.5-cp311-cp311-win32.whl            66 kB
  chacha20poly1305_reuseable-0.2.5-cp311-cp311-win_amd64.whl        66 kB
  chacha20poly1305_reuseable-0.2.5-cp37-cp37m-win32.whl             66 kB
  chacha20poly1305_reuseable-0.2.5-cp37-cp37m-win_amd64.whl         66 kB
  chacha20poly1305_reuseable-0.2.5-cp38-cp38-win32.whl              66 kB
  chacha20poly1305_reuseable-0.2.5-cp38-cp38-win_amd64.whl          66 kB
  chacha20poly1305_reuseable-0.2.5-cp39-cp39-win32.whl              66 kB
  chacha20poly1305_reuseable-0.2.5-cp39-cp39-win_amd64.whl          66 kB
  chacha20poly1305_reuseable-0.2.5-pp37-pypy37_pp73-win_amd64.whl   66 kB
  chacha20poly1305_reuseable-0.2.5-pp38-pypy38_pp73-win_amd64.whl   66 kB
  chacha20poly1305_reuseable-0.2.5-pp39-pypy39_pp73-win_amd64.whl   66 kB
```

**Comment by bdraco** [comment]
@postlund Can you try blowing away the venv cache ?

https://github.com/postlund/pyatv/actions/runs/4728869785/jobs/8395410792?pr=1956

**Comment by postlund** [comment]
@bdraco Tried it now, still the same it seems:

https://github.com/postlund/pyatv/actions/runs/5070940647/jobs/9106682133?pr=1993

**Comment by bdraco** [comment]
I don’t think it’s a problem with the binary though since we are using pypa ciwheelbuild and there isn’t anything outlandish. 

I looked through all the issues on ciwheelbuild and didn’t see anything related.

I don’t have a windows machine to test this locally so I’m at a loss on how to proceed

**Comment by postlund** [comment]
Yeah, I'm  not sure either. I did try it on my work laptop (Windows 10) and I didn't see the problem there. So I suspect it's something fishy with the GitHub runners.

**Comment by bdraco** [comment]
closing per https://github.com/postlund/pyatv/pull/2110
